[Dataset]
#Mode can be of type Range or Selected
Mode=Selected
VolumeNumber=71
VolumeRange=71
datapath =/groups/brooksgrp/laws/us_federal_statutes/Updated_2026-04-06
outputdir =/groups/brooksgrp/citizen_voice/python_output/statutes_broken_into_sections
agency=True

[Appropriations]
datapath =/groups/brooksgrp/citizen_voice/python_output/statutes_broken_into_sections/latest
outputdir =/groups/brooksgrp/citizen_voice/python_output/statutes_broken_into_sections/latest/appr

[Divisions]
datapath = /groups/brooksgrp/laws/us_federal_statutes/Updated_2026-04-06
filename = DivisionMapping

[KeyUpdate]
folder_to_update = /groups/brooksgrp/citizen_voice/consolidated_coded_statutes/Raw/Vol-133

[ExcelDir]
base_latest = /groups/brooksgrp/citizen_voice/python_output/statutes_broken_into_sections/latest
base_coded = /groups/brooksgrp/citizen_voice/consolidated_coded_statutes/
